### ISSUE TITLE
Greyed out, doesnt work.

### ISSUE THREAD

**Issue by tablatronix** [marian42/octoprint-preheat#28]
I don't get it.. Its greyed out, doesn't seem to work.

![Screen Shot 2019-11-01 at 9 19 06 PM](https://user-images.githubusercontent.com/807787/68064762-a22fc880-fced-11e9-90c8-022a1de817d3.png)

**Comment by marian42** [comment]
You need to select a file first.

**Comment by tablatronix** [comment]
ok, so what is the point of preheat if you have already have a file to print ?

I don't get it.. haha

**Comment by marian42** [comment]
I found that I often select a file and manually set the temperature to the printing temperature of the file. While it heats, I do other things like change the filament. When I'm ready and the printer is heated up, I start the print.

This plugin automates that. It reads the printing temperature from the file. That's why you need to select a file, it will set the printer to the temperature that the file will be printed with.

**Comment by tablatronix** [comment]
I see, its "Job preheat" , But i saw the defaults in the settings so assumed it could be used as a generic preheat also. i usually preheat when I am still working in fusion or iterating stuff, or slicing in cura, so I do not have a file to print yet. 

I guess I will use the custom commands plugin instead and use gcode.

I preheat to bed level also, to heat both tools at once etc.

**Comment by tablatronix** [comment]
So is this just a limitation you put in?

can I just mod this?

```PY
if (self._printer.get_current_job()["file"]["path"] == None):
   temperatures = self.get_fallback_temperatures()
```

**Comment by marian42** [comment]
I guess this could be added, it was also requested in #26.

**Comment by marian42** [comment]
It is now possible to preheat without selecting a file.
